# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coddpto', models.CharField(db_index=True, max_length=2, verbose_name=b'Code')),
                ('nom_dpto', models.CharField(max_length=50, verbose_name=b'Departamento')),
            ],
            options={
                'ordering': ('nom_dpto',),
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddist', models.CharField(db_index=True, max_length=6, verbose_name=b'IDDist')),
                ('coddpto', models.CharField(db_index=True, max_length=2, verbose_name=b'Code Departamento')),
                ('nom_dpto', models.CharField(max_length=50, verbose_name=b'Departamento')),
                ('codprov', models.CharField(db_index=True, max_length=2, verbose_name=b'Code Provincia')),
                ('nom_prov', models.CharField(max_length=50, verbose_name=b'Provincia')),
                ('coddist', models.CharField(db_index=True, max_length=2, verbose_name=b'Code Distrito')),
                ('nom_dist', models.CharField(max_length=50, verbose_name=b'Distrito')),
            ],
            options={
                'ordering': ('nom_dpto', 'nom_prov', 'nom_dist'),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprov', models.CharField(db_index=True, max_length=4, verbose_name=b'IDProv')),
                ('coddpto', models.CharField(db_index=True, max_length=2, verbose_name=b'Code Departamento')),
                ('nom_dpto', models.CharField(max_length=50, verbose_name=b'Departamento')),
                ('codprov', models.CharField(db_index=True, max_length=2, verbose_name=b'Code Provincia')),
                ('nom_prov', models.CharField(max_length=50, verbose_name=b'Provincia')),
            ],
            options={
                'ordering': ('nom_dpto', 'nom_prov'),
            },
        ),
    ]
