# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion', models.CharField(choices=[('mas', 'Aumento'), ('menos', 'Disminuye')], max_length=10)),
                ('total_dia', models.IntegerField(default=0)),
                ('mayorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Mayorista')),
            ],
        ),
    ]
