# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofcatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aumento', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('consumo', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha', models.DateField(blank=True)),
                ('total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.Insumo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.Producto')),
            ],
        ),
    ]
