# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='aumento',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='consumo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
