# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180716_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
