# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:16
from __future__ import unicode_literals

import catalogo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('seccion', models.CharField(blank=True, choices=[(b'genero', b'Genero'), (b'categoria', b'Categoria'), (b'estilo', b'Estilo'), (b'coleccion', b'Coleccion')], max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, max_length=120, unique=True)),
                ('titulo_seo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, max_length=250, null=True, upload_to=b'categorias')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('sku', models.CharField(blank=True, max_length=14, null=True)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True)),
                ('slug', models.CharField(editable=False, max_length=120, unique=True)),
                ('texto_variacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('video', models.CharField(blank=True, max_length=120, null=True)),
                ('es_oferta', models.BooleanField(default=False)),
                ('categorias', models.ManyToManyField(blank=True, related_name='categorias_producto', to='catalogo.Categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='etiquetas', to='catalogo.Etiqueta')),
                ('relaciones', models.ManyToManyField(blank=True, related_name='_producto_relaciones_+', to='catalogo.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=catalogo.models.url_imagen_pr)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='catalogo.Producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_minorista', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oferta', models.PositiveIntegerField(default=0)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='catalogo.Producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utiles.Talla')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicasproducto',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='catalogo.Producto'),
        ),
    ]
