# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=14, null=True),
        ),
    ]
