# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text=b'El titulo del bloque', max_length=100)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('contenido', models.TextField(blank=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[(b'imagenes', b'Imagenes'), (b'productos', b'Productos')], max_length=100)),
                ('num_mostrar', models.PositiveIntegerField(default=1)),
                ('navegacion', models.BooleanField(default=True)),
                ('items', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text=b'Titulo de Categoria', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text=b'El titulo para identificar el hero', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(upload_to=b'hero')),
                ('body', models.CharField(blank=True, help_text=b'El texto que se mostrara', max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100)),
                ('enlace', models.CharField(blank=True, max_length=100)),
                ('estilo_body', models.CharField(blank=True, help_text=b'Los estilos del texto que se mostrara', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCarrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text=b'Titulo que tendra la imagen en el Alt', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to=b'bloque/carrusel')),
                ('carrusel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='cmsweb.Carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='LinkMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('icono', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(blank=True, max_length=100)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text=b'El titulo de la pagina web', max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descripcion', models.CharField(help_text=b'La descripcion que se vera en la pagina para el buscador', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('contenido', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsweb.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='paginas',
            field=models.ManyToManyField(blank=True, related_name='menus', to='cmsweb.Pagina'),
        ),
        migrations.AddField(
            model_name='linkmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cmsweb.Menu'),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carruseles', to='cmsweb.Pagina'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='cmsweb.Pagina'),
        ),
    ]
