# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utiles', '0002_auto_20180524_2327'),
        ('cliente', '0001_initial'),
        ('ofcatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(blank=True, choices=[(b'und', b'Unidad'), (b'par', b'Par'), (b'fr', b'Fardo'), (b'pq', b'Paquete'), (b'm', b'Metros'), (b'cm', b'Centimetros')], max_length=30)),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mayorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Mayorista')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.Producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utiles.Serie')),
            ],
        ),
    ]
