# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '__first__'),
        ('cliente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_carro', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(choices=[(b'Abierto', 'Abierto - Actualmente activa  '), (b'Fusionada', 'Fusionada - sustituida por otra canasta '), (b'Guardado', 'Guardado - para los articulos para comprar mas adelante '), (b'Congelado', 'Congelado - la canasta no se puede modificar '), (b'Enviado', 'Enviado - ha sido ordenado en la caja')], default=b'Abierto', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('cupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.CuponDescuento')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='carro.Carro')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
                ('variacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ProductoVariacion')),
            ],
        ),
    ]
