# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='numberserie',
            name='serie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='utiles.Serie'),
        ),
        migrations.AddField(
            model_name='numberserie',
            name='talla',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='utiles.Talla'),
        ),
    ]
