# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='catalogo/insumo')),
                ('ancho', models.IntegerField(default=0)),
                ('superficie', models.IntegerField(default=0)),
                ('unidad', models.CharField(blank=True, choices=[(b'und', b'Unidad'), (b'par', b'Par'), (b'fr', b'Fardo'), (b'pq', b'Paquete'), (b'm', b'Metros'), (b'cm', b'Centimetros')], max_length=20)),
                ('stock_alert', models.IntegerField(default=0)),
                ('ratio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='catalogo/producto')),
                ('ecommerce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
                ('modelo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.ModeloProducto')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.Insumo')),
                ('modelo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.ModeloProducto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.TipoInsumo'),
        ),
    ]
