# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '__first__'),
        ('ofcatalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0)),
                ('unidad', models.CharField(blank=True, choices=[(b'und', b'Unidad'), (b'par', b'Par'), (b'fr', b'Fardo'), (b'pq', b'Paquete'), (b'm', b'Metros'), (b'cm', b'Centimetros')], max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('insumo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ofcatalogo.Insumo')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario')),
            ],
        ),
    ]
